### ISSUE TITLE
"Object xxx is not a tag" during release init

### ISSUE THREAD

**Issue by stromnet** [danielflower/multi-module-maven-release-plugin#12]
Hi,

having some issues releasing 1.0.1 of my modules (i.e. only 1.0.0 has ever been released before).
During init I get this:

```
[ERROR] Failed to execute goal com.github.danielflower.mavenplugins:multi-module-maven-release-plugin:1.4.0:release (default-cli) on project fileservice: Error while looking up tag Ref[refs/tags/fileservice-1.0.0=eb81113cebac4c30c517a360e70194d284c8ca38]: Object eb81113cebac4c30c517a360e70194d284c8ca38 is not a tag. -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal com.github.danielflower.mavenplugins:multi-module-maven-release-plugin:1.4.0:release (default-cli) on project fileservice: Error while looking up tag Ref[refs/tags/fileservice-1.0.0=eb81113cebac4c30c517a360e70194d284c8ca38]
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:216)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:120)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:355)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:155)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:584)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:216)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:160)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoExecutionException: Error while looking up tag Ref[refs/tags/fileservice-1.0.0=eb81113cebac4c30c517a360e70194d284c8ca38]
	at com.github.danielflower.mavenplugins.release.AnnotatedTagFinder.tagsForVersion(AnnotatedTagFinder.java:30)
	at com.github.danielflower.mavenplugins.release.Reactor.fromProjects(Reactor.java:37)
	at com.github.danielflower.mavenplugins.release.ReleaseMojo.execute(ReleaseMojo.java:123)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:132)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
	... 19 more
Caused by: org.eclipse.jgit.errors.IncorrectObjectTypeException: Object eb81113cebac4c30c517a360e70194d284c8ca38 is not a tag.
	at org.eclipse.jgit.revwalk.RevWalk.parseTag(RevWalk.java:815)
	at com.github.danielflower.mavenplugins.release.AnnotatedTag.fromRef(AnnotatedTag.java:44)
	at com.github.danielflower.mavenplugins.release.AnnotatedTagFinder.tagsForVersion(AnnotatedTagFinder.java:28)
	... 23 more
```

The following tags exists:
```
$ 
git show-ref --tags
eb81113cebac4c30c517a360e70194d284c8ca38 refs/tags/fileservice-1.0.0
eb81113cebac4c30c517a360e70194d284c8ca38 refs/tags/fs-api-1.0.0
eb81113cebac4c30c517a360e70194d284c8ca38 refs/tags/fs-api-extra-1.0.0
eb81113cebac4c30c517a360e70194d284c8ca38 refs/tags/fs-client-1.0.0
eb81113cebac4c30c517a360e70194d284c8ca38 refs/tags/fs-server-1.0.0
```

fileservice is the root pom artifact, and the others are sub-modules.

Looking at the code, I cannot really see why this would happen.. AnnotatedTag.fromRef is called with tag which is directly derived from git.tagList().call();...

Tested with com.github.danielflower.mavenplugins:multi-module-maven-release-plugin:jar:1.4.0, and org.eclipse.jgit:org.eclipse.jgit:jar:3.7.1.201504261725 (also tested with jgit 4.0.2.201509141540-r, no success).

Any ideas?

**Comment by stromnet** [comment]
Also tried version 1.3.1 of multi-module-maven-release-plugin without success.. 
Weird thing is, another project repo which is setup more or less the exact same way, released just fine..

**Comment by stromnet** [comment]
Found the issue. the fileservice-1.0.0 tag was not annotated (git show fileservice-1.0.0 did not show any tag/annotation info, which is usually shown). Not sure how it ended up like this, did I create this manually or something?...

Well, the solution was simple:
* Checkout code at fileservice-1.0.0 (which all other also pointed to)
* Remove the tags from local and from remo repo
* Re-run releaser, which re-created the 1.0.0 tags, now with annotations
* Checkout HEAD
* Re-run releaser, which now releases the new version
