### ISSUE TITLE
Git SSH authentication failing 

### ISSUE THREAD

**Issue by yeshamavani** [danielflower/multi-module-maven-release-plugin#137]
Hello 
I am trying to use the plugin to publish my artifacts to maven central I have a multi module design something like a monorepo with multiple maven projects 
1. I have 2FA enabled on my git account 
2. Here is the link to my repo --- https://github.com/yeshamavani/springmono
3. I have referred the SSH configuration needed for this, mentioned over here -- https://danielflower.github.io/multi-module-maven-release-plugin/ssh-authentication.html
4. As per the doc I have also mentioned the config in settings.xml file at my Maven_home
5. I even generated new SSH key that has -----BEGIN RSA PRIVATE KEY-----  as the starting of my private key file

![image](https://user-images.githubusercontent.com/83634146/229466817-ada9a6c2-e6dd-497e-b660-34f4617c4358.png)
![image](https://user-images.githubusercontent.com/83634146/229466858-8e01c8cc-700e-43a3-a08f-275ab0edcb02.png)

![image](https://user-images.githubusercontent.com/83634146/229467055-78eeafbb-d5ad-4565-9628-47b187b7998e.png)

**Comment by yeshamavani** [comment]
Attaching the complete error log 

[WARNING] Parameter 'localRepository' (user property 'localRepository') is deprecated core expression; Avoid use of ArtifactRepository type. If you need access to local repository, switch to '${repositorySystemSession}' expression and get LRM from it instead.
[ERROR] 
[ERROR] 
[ERROR] 
[ERROR] ************************************
[ERROR] Could not execute the release plugin
[ERROR] ************************************
[ERROR] 
[ERROR] 
[ERROR] There was an error while accessing the Git repository. The error returned from git was:
[ERROR] ssh://github.com/yeshamavani/springmono.git: Auth fail
[ERROR] Stack trace:
[ERROR] org.eclipse.jgit.api.errors.TransportException: ssh://github.com/yeshamavani/springmono.git: Auth fail
        at org.eclipse.jgit.api.LsRemoteCommand.execute(LsRemoteCommand.java:189)
        at org.eclipse.jgit.api.LsRemoteCommand.call(LsRemoteCommand.java:128)
        at com.github.danielflower.mavenplugins.release.RemoteTagFetcher.getTags(LocalGitRepo.java:256)
        at com.github.danielflower.mavenplugins.release.LocalGitRepo.allTags(LocalGitRepo.java:222)
        at com.github.danielflower.mavenplugins.release.Reactor.getRemoteBuildNumbers(Reactor.java:149)
        at com.github.danielflower.mavenplugins.release.Reactor.fromProjects(Reactor.java:52)
        at com.github.danielflower.mavenplugins.release.ReleaseMojo.execute(ReleaseMojo.java:162)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:126)
        at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute2(MojoExecutor.java:342)
        at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute(MojoExecutor.java:330)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:213)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:175)
        at org.apache.maven.lifecycle.internal.MojoExecutor.access$000(MojoExecutor.java:76)
        at org.apache.maven.lifecycle.internal.MojoExecutor$1.run(MojoExecutor.java:163)
        at org.apache.maven.plugin.DefaultMojosExecutionStrategy.execute(DefaultMojosExecutionStrategy.java:39)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:160)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:105)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:73)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:53)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:118)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:261)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:173)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:101)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:827)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:272)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:195)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:282)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:225)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:406)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:347)
Caused by: org.eclipse.jgit.errors.TransportException: ssh://github.com/yeshamavani/springmono.git: Auth fail
        at org.eclipse.jgit.transport.JschConfigSessionFactory.getSession(JschConfigSessionFactory.java:162)
        at org.eclipse.jgit.transport.SshTransport.getSession(SshTransport.java:107)
        at org.eclipse.jgit.transport.TransportGitSsh$SshFetchConnection.<init>(TransportGitSsh.java:281)
        at org.eclipse.jgit.transport.TransportGitSsh.openFetch(TransportGitSsh.java:153)
        at org.eclipse.jgit.api.LsRemoteCommand.execute(LsRemoteCommand.java:167)
        ... 33 more
Caused by: com.jcraft.jsch.JSchException: Auth fail
        at com.jcraft.jsch.Session.connect(Session.java:519)
        at org.eclipse.jgit.transport.JschConfigSessionFactory.getSession(JschConfigSessionFactory.java:115)
        ... 37 more

[ERROR] 
[ERROR] 
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] springmono 0.0.1 ................................... FAILURE [  8.861 s]
[INFO] packages 0.0.1 ..................................... SKIPPED
[INFO] core 0.0.1-SNAPSHOT ................................ SKIPPED
[INFO] services 0.0.1 ..................................... SKIPPED
[INFO] mainservice 0.0.1-SNAPSHOT ......................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  9.929 s
[INFO] Finished at: 2023-04-03T13:36:54+05:30
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.github.danielflower.mavenplugins:multi-module-maven-release-plugin:3.6.4:release (default-cli) on project springmono: Could not release due to a Git error -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

**Comment by mileshbhana** [comment]
I'm getting a similar issue with Bitbucket. 

My key begins with 
-----BEGIN OPENSSH PRIVATE KEY-----

It seems that the library being used jsch doesn't support this format, which is now required by Bitbucket. 
https://stackoverflow.com/questions/53134212/invalid-privatekey-when-using-jsch

Are there any plans to support the newer OpenSSH keys? 


Stacktrace Below:


There was an error while accessing the Git repository. The error returned from git was:
[ERROR] git@bitbucket.org:<repo_name>: invalid privatekey: [B@4a1e3ac1
[ERROR] Stack trace:
[ERROR] org.eclipse.jgit.api.errors.TransportException: git@bitbucket.org:<repo_name>: invalid privatekey: [B@4a1e3ac1
	at org.eclipse.jgit.api.LsRemoteCommand.execute(LsRemoteCommand.java:189)
	at org.eclipse.jgit.api.LsRemoteCommand.call(LsRemoteCommand.java:128)
	at com.github.danielflower.mavenplugins.release.RemoteTagFetcher.getTags(LocalGitRepo.java:256)
	at com.github.danielflower.mavenplugins.release.LocalGitRepo.allTags(LocalGitRepo.java:222)
	at com.github.danielflower.mavenplugins.release.Reactor.getRemoteBuildNumbers(Reactor.java:149)
	at com.github.danielflower.mavenplugins.release.Reactor.fromProjects(Reactor.java:52)
	at com.github.danielflower.mavenplugins.release.ReleaseMojo.execute(ReleaseMojo.java:162)


Caused by: com.jcraft.jsch.JSchException: invalid privatekey: [B@4a1e3ac1
	at com.jcraft.jsch.KeyPair.load(KeyPair.java:664)
	at com.jcraft.jsch.KeyPair.load(KeyPair.java:561)
	at com.jcraft.jsch.IdentityFile.newInstance(IdentityFile.java:40)
	at com.jcraft.jsch.JSch.addIdentity(JSch.java:406)
	at com.jcraft.jsch.JSch.addIdentity(JSch.java:366)
	at org.eclipse.jgit.transport.JschConfigSessionFactory.getJSch(JschConfigSessionFactory.java:383)
	at org.eclipse.jgit.transport.JschConfigSessionFactory.createSession(JschConfigSessionFactory.java:317)
	at org.eclipse.jgit.transport.JschConfigSessionFactory.createSession(JschConfigSessionFactory.java:184)
	at org.eclipse.jgit.transport.JschConfigSessionFactory.getSession(JschConfigSessionFactory.java:108)
	... 32 more

**Comment by haroon-sheikh** [comment]
Hi @danielflower, do you have any advise on this `You're using an RSA key with SHA-1, which is no longer allowed.`

I've tried creating keys with `rsa`, `ecdsa` and `ed25519` and none of these seem to work for me. It's either erroring with invalid private key or the above error.

https://github.blog/security/application-security/improving-git-protocol-security-github/
