### ISSUE TITLE
Object xxx is not a tag

### ISSUE THREAD

**Issue by pdudits** [danielflower/multi-module-maven-release-plugin#31]
I'm trying to migrate [soundlibs](https://github.com/pdudits/soundlibs/tree/multi-module-release), and the trying to run `releaser:next` fails with:

````
[ERROR] Failed to execute goal com.github.danielflower.mavenplugins:multi-module-maven-release-plugin:2.0.3:next (default-cli) on project soundlibs:

Caused by: org.apache.maven.plugin.MojoExecutionException: Error while looking up tag Ref[refs/tags/soundlibs-1.2=41001253ddbbc429b2de4dbc2efb1a1d93c75806]
        at com.github.danielflower.mavenplugins.release.AnnotatedTagFinder.tagsForVersion(AnnotatedTagFinder.java:30)
        at com.github.danielflower.mavenplugins.release.Reactor.fromProjects(Reactor.java:37)
        at com.github.danielflower.mavenplugins.release.NextMojo.execute(NextMojo.java:39)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
        ... 20 more
Caused by: org.eclipse.jgit.errors.IncorrectObjectTypeException: Object 41001253ddbbc429b2de4dbc2efb1a1d93c75806 is not a tag.
        at org.eclipse.jgit.revwalk.RevWalk.parseTag(RevWalk.java:834)
        at com.github.danielflower.mavenplugins.release.AnnotatedTag.fromRef(AnnotatedTag.java:44)
        at com.github.danielflower.mavenplugins.release.AnnotatedTagFinder.tagsForVersion(AnnotatedTagFinder.java:28)
        ... 24 more
````

First idea was to just unpack refs, into refs/tags, but that wasn't enough.

**Comment by danielflower** [comment]
For some reason the plugin is taking an interest in one of the commits from the old maven release plugin:

    $ git cat-file -p 41001253ddbbc429b2de4dbc2efb1a1d93c75806
    tree ec937ea08b3100006b40393f677fb53333438357
    parent aed2f78100ab065666edb3bd3a31b304cf15773e
    author pdudits <pdudits@localhost> 1360019197 +0100
    committer pdudits <pdudits@localhost> 1360019197 +0100
    
    [maven-release-plugin] prepare release soundlibs-1.2

I'll have a look to see why.

**Comment by pdudits** [comment]
Yes, but that commit points to is an actual tagged release. The difference is, that while 1.3 was built with git, 1.2 was yet done in Mercurial on googlecode. Maybe the github exporter used different kind of tag (I've seen metioning "lightweight tags" over at this [stackoverflow question](http://stackoverflow.com/questions/29892210/get-message-of-tags-using-jgit))

**Comment by danielflower** [comment]
Yeah, it may well have been due to it been a lightweight tag. Fixed now. Please use verison `2.0.4`
