### ISSUE TITLE
invalid privatekey

### ISSUE THREAD

**Issue by AriesWmj** [danielflower/multi-module-maven-release-plugin#87]

**Comment by AriesWmj** [comment]
I use  mvn -X releaser:release -DmodulesToRelease=wallet-omni which wallet-omni is my module name。with maven 3.5.4 and java 1.8 on Mac

I follow this http://danielflower.github.io/multi-module-maven-release-plugin/ssh-authentication.html to specify my private key.
then the ERROR info is :

[ERROR] 
[ERROR] 
[ERROR] 
[ERROR] ************************************
[ERROR] Could not execute the release plugin
[ERROR] ************************************
[ERROR] 
[ERROR] 
[ERROR] There was an error while accessing the Git repository. The error returned from git was:
[ERROR] ssh://git@XXXXXXXX.git: invalid privatekey: [B@301d8120
[ERROR] Stack trace:
[ERROR] org.eclipse.jgit.api.errors.TransportException: ssh://git@XXXXXXXXX.git: invalid privatekey: [B@301d8120
        at org.eclipse.jgit.api.LsRemoteCommand.execute(LsRemoteCommand.java:222)
        at org.eclipse.jgit.api.LsRemoteCommand.call(LsRemoteCommand.java:161)
        at com.github.danielflower.mavenplugins.release.RemoteTagFetcher.getTags(LocalGitRepo.java:255)
        at com.github.danielflower.mavenplugins.release.LocalGitRepo.allTags(LocalGitRepo.java:221)
        at com.github.danielflower.mavenplugins.release.Reactor.getRemoteBuildNumbers(Reactor.java:149)
        at com.github.danielflower.mavenplugins.release.Reactor.fromProjects(Reactor.java:52)
        at com.github.danielflower.mavenplugins.release.ReleaseMojo.execute(ReleaseMojo.java:127)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:154)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:146)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:56)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:305)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:192)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:105)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:954)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:192)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.eclipse.jgit.errors.TransportException: ssh:/XXXXXXXXXX.git: invalid privatekey: [B@301d8120
        at org.eclipse.jgit.transport.JschConfigSessionFactory.getSession(JschConfigSessionFactory.java:191)
        at org.eclipse.jgit.transport.SshTransport.getSession(SshTransport.java:140)
        at org.eclipse.jgit.transport.TransportGitSsh$SshFetchConnection.<init>(TransportGitSsh.java:280)
        at org.eclipse.jgit.transport.TransportGitSsh.openFetch(TransportGitSsh.java:170)
        at org.eclipse.jgit.api.LsRemoteCommand.execute(LsRemoteCommand.java:200)
        ... 28 more
Caused by: com.jcraft.jsch.JSchException: invalid privatekey: [B@301d8120
        at com.jcraft.jsch.KeyPair.load(KeyPair.java:664)
        at com.jcraft.jsch.KeyPair.load(KeyPair.java:561)
        at com.jcraft.jsch.IdentityFile.newInstance(IdentityFile.java:40)
        at com.jcraft.jsch.JSch.addIdentity(JSch.java:406)
        at com.jcraft.jsch.JSch.addIdentity(JSch.java:387)
        at com.github.danielflower.mavenplugins.release.SshAgentSessionFactory.createDefaultJSch(SshAgentSessionFactory.java:99)
        at org.eclipse.jgit.transport.JschConfigSessionFactory.getJSch(JschConfigSessionFactory.java:377)
        at org.eclipse.jgit.transport.JschConfigSessionFactory.createSession(JschConfigSessionFactory.java:335)
        at org.eclipse.jgit.transport.JschConfigSessionFactory.createSession(JschConfigSessionFactory.java:208)
        at org.eclipse.jgit.transport.JschConfigSessionFactory.getSession(JschConfigSessionFactory.java:138)
        ... 32 more

[ERROR] 
[ERROR]

**Comment by AriesWmj** [comment]
I have found the problem.
description as following:
https://stackoverflow.com/questions/53134212/invalid-privatekey-when-using-jsch
